### ISSUE TITLE
Apple M1 Pro  macos Ventura 13.4.1

### ISSUE THREAD

**Issue by phpmaple** [responsively-org/responsively-app#1057]
<pre><code>
09:52:13.669 › Checking for update
[4646:0830/095214.618734:ERROR:extensions_browser_client.cc(67)] Extension Error:
  OTR:     false
  Level:   1
  Source:  manifest.json
  Message: Service worker registration failed. Status code: 2
  ID:      mmbjomaajjjajabbhebdklijblophbbm
  Type:    ManifestError
[4646:0830/095215.631078:ERROR:service_worker_storage.cc(2016)] Failed to delete the database: Database IO error
09:52:16.474 › Update for version 1.7.0 is not available (latest version: 1.7.0, downgrade is disallowed).
09:52:16.475 › checkForUpdatesAndNotify called, downloadPromise is null

Uncaught Exception:
TypeError: The argument 'options' is invalid. Received { port: false }
at new NodeError (node:internal/errors:399:5)
at Server.listen (node:net:1927:9)
at module.exports.plugin (/Applications/ResponsivelyApp.app/Contents/Resources/app.asar/node_modules/browser-sync/lib/server/index.js:37:25)
at Object.startServer [as fn] (/Applications/ResponsivelyApp.app/Contents/Resources/app.asar/node_modules/browser-sync/lib/async.js:210:52)
at /Applications/ResponsivelyApp.app/Contents/Resources/app.asar/node_modules/browser-sync/lib/browser-sync.js:141:14
at iterate (/Applications/ResponsivelyApp.app/Contents/Resources/app.asar/node_modules/browser-sync/lib/utils.ts:298:9)
at /Applications/ResponsivelyApp.app/Contents/Resources/app.asar/node_modules/browser-sync/lib/utils.ts:307:21
at executeTask (/Applications/ResponsivelyApp.app/Contents/Resources/app.asar/node_modules/browser-sync/lib/browser-sync.js:161:13)
at Object.mergeMiddlewares [as fn] (/Applications/ResponsivelyApp.app/Contents/Resources/app.asar/node_modules/browser-sync/lib/async.js:196:9)
at /Applications/ResponsivelyApp.app/Contents/Resources/app.asar/node_modules/browser-sync/lib/browser-sync.js:141:14

</code></pre>

**Comment by liangyi9812** [comment]
> Having the same issue with an intel chip mac, you find a solution for this?

same issue!!!

**Comment by SpencerPaukstis** [comment]
> > Having the same issue with an intel chip mac, you find a solution for this?
> 
> same issue!!!

Try connecting to a vpn, that was the only way I was able to get it to work
