### ISSUE TITLE
Error when trying to download dependencies

### ISSUE THREAD

**Issue by LauraAbCoronel** [responsively-org/responsively-app#672]
# 🐞 bug report

### ✍️ Description
Error occurs when I try to install dependencies running <code>yarn</code> in the terminal

### 🕵🏼‍♂️ Is this a regression?
No

### 🔬 Minimal Reproduction
I forked and cloned the repo.
In the terminal after navigating to <code>desktop-app</code> I try to run <code>yarn</code> and an error occurs.

### 🌍 Your Environment

<pre><code>macOS Monterey v12.3.1
M1 chip
</code></pre>

### 🔥 Exception or Error or Screenshot

<pre><code>
kirby@Lauras-MacBook-Pro desktop-app % yarn
yarn install v1.22.18
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > eslint-config-airbnb@17.1.1" has incorrect peer dependency "eslint-plugin-jsx-a11y@^6.2.3".
warning "eslint-plugin-jest > @typescript-eslint/experimental-utils > @typescript-eslint/typescript-estree > tsutils@3.17.1" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
warning " > stylelint-config-prettier@4.0.0" has incorrect peer dependency "stylelint@^9.1.1".
warning " > stylelint-config-standard@18.3.0" has incorrect peer dependency "stylelint@^8.3.0 || ^9.0.0 || ^10.0.0".
warning "stylelint-config-standard > stylelint-config-recommended@2.2.0" has incorrect peer dependency "stylelint@^8.3.0 || ^9.0.0 || ^10.0.0".
[4/4] 🔨  Building fresh packages...
[-/7] ⢀ waiting...
[2/7] ⢀ fsevents
[7/7] ⢀ electron
[-/7] ⢀ waiting...
error /Users/kirby/Code/responsively-app/desktop-app/node_modules/electron: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /Users/kirby/Code/responsively-app/desktop-app/node_modules/electron
Output:
HTTPError: Response code 404 (Not Found) for https://github.com/electron/electron/releases/download/v9.3.1/electron-v9.3.1-darwin-arm64.zip
    at EventEmitter.<anonymous> (/Users/kirby/Code/responsively-app/desktop-app/node_modules/got/source/as-stream.js:35:24)
    at EventEmitter.emit (node:events:527:28)
    at module.exports (/Users/kirby/Code/responsively-app/desktop-app/node_modules/got/source/get-response.js:22:10)
    at ClientRequest.handleResponse (/Users/kirby/Code/responsively-app/desktop-app/node_modules/got/source/request-as-event-emitter.js:155:5)
    at Object.onceWrapper (node:events:642:26)
    at ClientRequest.emit (node:events:539:35)
    at ClientRequest.origin.emit (/Users/kirby/Code/responsively-app/desktop-app/node_modules/@szmarczak/http-timer/source/index.js:37:11)
</code></pre>

**Comment by LauraAbCoronel** [comment]
It looks like maybe the electron version this project is on doesn't have a version for the M1 chip?
