### ISSUE TITLE
Cannot install v1.0.0-alpha Release!

### ISSUE THREAD

**Issue by TigersWay** [responsively-org/responsively-app#734]
# 🐞 bug report

### ✍️ Description

Just installed the new alpha release and got
![error](https://user-images.githubusercontent.com/114064/196074850-51e55981-7f8c-4684-99eb-3703f536f653.png)

### 🕵🏼‍♂️ Is this a regression?
...

### 🔬 Minimal Reproduction
Just install

### 🌍 Your Environment
Windows 11

**Comment by manojVivek** [comment]
Confirmed this is happening on Mac as well, looking into it.

**Comment by tarasis** [comment]
Yup, same on macOS 13 beta. Tried nuking the ~/Library/Application Support/ResponsivelyApp folder but it made no difference.

```
Uncaught Exception:
Error: ENOENT, dist/templates/plugin.tmpl not found in /Applications/ResponsivelyApp.app/Contents/Resources/app.asar
at createError (node:electron/js2c/asar_bundle:5:1255)
at e.readFileSync (node:electron/js2c/asar_bundle:5:9330)
at l (/Applications/ResponsivelyApp.app/Contents/Resources/app.asar/dist/main/main.js:2:210534)
at 38512 (/Applications/ResponsivelyApp.app/Contents/Resources/app.asar/dist/main/main.js:2:210337)
at __webpack_require__ (/Applications/ResponsivelyApp.app/Contents/Resources/app.asar/dist/main/main.js:8:1560894)
at 19810 (/Applications/ResponsivelyApp.app/Contents/Resources/app.asar/dist/main/main.js:2:203654)
at __webpack_require__ (/Applications/ResponsivelyApp.app/Contents/Resources/app.asar/dist/main/main.js:8:1560894)
at 99988 (/Applications/ResponsivelyApp.app/Contents/Resources/app.asar/dist/main/main.js:2:203218)
at __webpack_require__ (/Applications/ResponsivelyApp.app/Contents/Resources/app.asar/dist/main/main.js:8:1560894)
at 34597 (/Applications/ResponsivelyApp.app/Contents/Resources/app.asar/dist/main/main.js:2:231940)
```
